#!/bin/bash

# Eventura Quick Start Guide
# Run this script to see all available commands

clear

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║              🎉  EVENTURA - Quick Start Guide  🎉          ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Current Directory: $(pwd)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 GETTING STARTED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Install Dependencies:"
echo "   cd client && npm install"
echo ""
echo "2️⃣  Start Development Server:"
echo "   npm run dev"
echo ""
echo "3️⃣  Open in Browser:"
echo "   http://localhost:3000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔐 DEMO LOGIN CREDENTIALS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👤 Student Account:"
echo "   Email:    john@neub.edu.bd"
echo "   Password: password123"
echo ""
echo "👤 Organizer Account:"
echo "   Email:    jane@neub.edu.bd"
echo "   Password: password123"
echo ""
echo "👤 Admin Account:"
echo "   Email:    admin@neub.edu.bd"
echo "   Password: password123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📦 NPM COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Development:"
echo "   npm run dev      - Start dev server with hot reload"
echo ""
echo "Production:"
echo "   npm run build    - Build for production"
echo "   npm run preview  - Preview production build"
echo ""
echo "Quality:"
echo "   npm run lint     - Run ESLint"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📁 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "client/"
echo "├── src/"
echo "│   ├── components/     - React components"
echo "│   ├── pages/          - Page components"
echo "│   ├── context/        - State management"
echo "│   ├── hooks/          - Custom hooks"
echo "│   ├── services/       - API services (mock)"
echo "│   └── utils/          - Helper functions"
echo "├── public/             - Static files"
echo "└── Configuration files"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 README.md                  - Project overview"
echo "📄 COMPLETE_SUMMARY.md        - Migration summary"
echo "📄 PROJECT_STRUCTURE.md       - Detailed structure"
echo "📄 ARCHITECTURE.md            - System architecture"
echo "📄 DEVELOPMENT_CHECKLIST.md   - Feature checklist"
echo "📄 CHEAT_SHEET.md             - Quick reference"
echo "📄 client/README.md           - Client documentation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✨ KEY FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ React 18 with hooks"
echo "✅ Tailwind CSS styling"
echo "✅ React Router navigation"
echo "✅ Context API state management"
echo "✅ Mock authentication system"
echo "✅ Toast notifications"
echo "✅ Responsive design"
echo "✅ Lucide React icons"
echo "✅ Date formatting utilities"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎯 IMPLEMENTED PAGES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Home         - Landing page with featured events"
echo "✅ Events       - Event listing with filters"
echo "✅ Login        - User authentication"
echo "⏳ Register     - Coming soon"
echo "⏳ EventDetails - Coming soon"
echo "⏳ Organizations- Coming soon"
echo "⏳ Dashboard    - Coming soon"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔧 TECH STACK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Frontend:    React 18.2.0"
echo "Styling:     Tailwind CSS 3.4.1"
echo "Router:      React Router v6.22.0"
echo "Build Tool:  Vite 5.1.4"
echo "Icons:       Lucide React 0.344.0"
echo "Toast:       React Hot Toast 2.4.1"
echo "HTTP:        Axios 1.6.7"
echo "Dates:       date-fns 3.3.1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Port already in use?"
echo "   Kill process: lsof -ti:3000 | xargs kill -9"
echo ""
echo "❌ Module not found?"
echo "   Delete node_modules and reinstall:"
echo "   rm -rf node_modules package-lock.json"
echo "   npm install"
echo ""
echo "❌ Build errors?"
echo "   Clear cache and rebuild:"
echo "   rm -rf dist .vite"
echo "   npm run build"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 QUICK START (AUTOMATED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run the automated setup script:"
echo "   chmod +x setup-react.sh"
echo "   ./setup-react.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📞 NEED HELP?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Check the documentation files above"
echo "💡 Review CHEAT_SHEET.md for common patterns"
echo "📖 See DEVELOPMENT_CHECKLIST.md for roadmap"
echo "🏗️  Read ARCHITECTURE.md for system design"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Ready to start coding! Happy developing! 🚀"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
